dldprma/team03

appfinal/src/App.jsx
appfinal/src/components/Footer.jsx
appfinal/src/components/Header.jsx
appfinal/src/components/Layout.jsx
appfinal/src/pages/Bus.jsx
appfinal/src/pages/Traffic.jsx
appfinal/src/pages/Train.jsx

250127 Design

---

appfinal/src/App.jsx
appfinal/src/components/Footer.jsx

250127 design : css 수정

---

appfinal/src/App.jsx
appfinal/src/pages/FirstEnrollStay.jsx

250127 : Feat

---

appfinal/src/components/TrainCalendar.jsx
appfinal/src/pages/Bus.jsx
appfinal/src/pages/Train.jsx

- 버스 페이지 구현
- 기차 페이지 구현
- 버스 출발지 도착지 스왑 함수 구현

250127 : design

---

appfinal/src/pages/traffic/ArrivalStationList.jsx
appfinal/src/pages/traffic/ArrivalTerminalList.jsx
appfinal/src/pages/traffic/Bus.jsx
appfinal/src/pages/traffic/BusCalendar.jsx
appfinal/src/pages/traffic/BusDetail.jsx
appfinal/src/pages/traffic/StartStationList.jsx
appfinal/src/pages/traffic/StartTerminalList.jsx
appfinal/src/pages/traffic/Traffic.jsx
appfinal/src/pages/traffic/Train.jsx
appfinal/src/pages/traffic/TrainCalendar.jsx
appfinal/src/pages/traffic/TrainDetail.jsx
appfinal/src/redux/terminalSlice.jsx

- 기차,버스 승차권 조회 기능구현
- 기차,버스 상세조회 페이지 구현

250211 FEATURE

---

appfinal/src/components/reservationInfo/ReservationCard.jsx
appfinal/src/components/reservationInfo/SpaceReservationCard.jsx
appfinal/src/pages/guest/guestMenu/Message.jsx
appfinal/src/pages/guest/guestMenu/SpaceCancle.jsx
appfinal/src/pages/guest/guestMenu/SpaceDetail.jsx
appfinal/src/pages/guest/guestMenu/StayDetail.jsx
appfinal/src/pages/host/hostMenu/HostMenu.jsx
appfinal/src/pages/host/hostMenu/SpaceCancleResrv.jsx
appfinal/src/pages/host/hostMenu/StayCancleResrv.jsx
appfinal/src/pages/host/hostMenu/StayResrv.jsx

250215 design 숙소 공간 컴포넌트 수정

---

appfinal/src/pages/slog/Slog.jsx
appfinal/src/pages/slog/SlogList.jsx
appfinal/src/pages/slog/SlogWrite.jsx
springfinal/src/main/java/com/kh/springfinal/SpringfinalApplication.java
springfinal/src/main/java/com/kh/springfinal/slog/SlogConfig.java
springfinal/src/main/java/com/kh/springfinal/slog/SlogController.java
springfinal/src/main/java/com/kh/springfinal/slog/SlogMapper.java
springfinal/src/main/java/com/kh/springfinal/slog/SlogService.java
springfinal/src/main/java/com/kh/springfinal/slog/SlogVo.java

- S-LOG (Controller, Service, Mapper, VO, Config) 백엔드 로직 구현
- S-LOG 이미지 파일 S3 업로드 기능 구현
- S-LOG 글씨 크기, 글씨체, 글씨 색깔, 가운데 정렬, 왼쪽 정렬 기능 구현
- S-LOG CONTENT값 DB에 <img><div> 형태로 넣는 기능 구현

250219: FEAT

---

appfinal/src/components/FilterBar/CalendalTime.jsx
appfinal/src/pages/space/FindSpaceDetail.jsx
appfinal/src/redux/spaceSlice.jsx
springfinal/src/main/java/com/kh/springfinal/space/SpaceController.java
springfinal/src/main/java/com/kh/springfinal/space/SpaceMapper.java
springfinal/src/main/java/com/kh/springfinal/space/SpaceService.java

20250219 FEAT : 공간 낮,밤 패키지 모두 예약된 날짜 막는 기능

---

appfinal/src/App.jsx
appfinal/src/components/map/MapRec.jsx
appfinal/src/pages/slog/Slog.jsx
appfinal/src/pages/slog/SlogCard.jsx
appfinal/src/pages/slog/SlogDetail.jsx
appfinal/src/pages/slog/SlogList.jsx
appfinal/src/redux/slogDetailSlice.jsx
appfinal/src/redux/slogRecSlice.jsx
appfinal/src/redux/slogSlice.jsx
springfinal/src/main/java/com/kh/springfinal/slog/RecPlaceVo.java
springfinal/src/main/java/com/kh/springfinal/slog/SlogConfig.java
springfinal/src/main/java/com/kh/springfinal/slog/SlogController.java
springfinal/src/main/java/com/kh/springfinal/slog/SlogMapper.java
springfinal/src/main/java/com/kh/springfinal/slog/SlogService.java

- S-LOG 리스트 불러오기
- S-LOG 상세조회 화면 db에서 불러오기
- S-LOG 카카오맵으로 추천장소 위치 띄우기

250221: FEAT

---

appfinal/src/components/Layout.jsx
appfinal/src/components/map/MapRec.jsx
appfinal/src/pages/slog/Slog.jsx
appfinal/src/pages/slog/SlogDetail.jsx
appfinal/src/pages/slog/SlogWrite.jsx
springfinal/src/main/java/com/kh/springfinal/slog/SlogController.java
springfinal/src/main/java/com/kh/springfinal/slog/SlogMapper.java
springfinal/src/main/java/com/kh/springfinal/slog/SlogService.java

- S-LOG 삭제하기 기능 추가
- S-LOG 수정하기 기존 값 불러오는 기능 추가
- S-LOG 추천 장소 화면 출력 기능 추가

250224 FEAT

---

appfinal/src/components/Header.jsx
appfinal/src/components/Layout.jsx
appfinal/src/pages/slog/KakaoShare.jsx
appfinal/src/pages/slog/Slog.jsx
appfinal/src/pages/slog/SlogCard.jsx
appfinal/src/pages/slog/SlogDetail.jsx
appfinal/src/pages/slog/SlogWrite.jsx
appfinal/src/redux/slogDetailSlice.jsx
appfinal/src/redux/store.jsx
springfinal/src/main/java/com/kh/springfinal/slog/SlogController.java
springfinal/src/main/java/com/kh/springfinal/slog/SlogMapper.java
springfinal/src/main/java/com/kh/springfinal/slog/SlogService.java
springfinal/src/main/java/com/kh/springfinal/slog/SlogVo.java

- 카카오톡 공유하기 기능 추가
- 에디터 업로드 사진 개별 삭제 기능 추가
- 타이틀 썸네일 사진 업로드 기능 추가

250226:FEAT

---

appfinal/src/components/Layout.jsx
appfinal/src/pages/slog/SlogDetail.jsx
appfinal/src/pages/slog/SlogWrite.jsx
appfinal/src/redux/slogSlice.jsx
springfinal/src/main/java/com/kh/springfinal/slog/SlogController.java
springfinal/src/main/java/com/kh/springfinal/slog/SlogMapper.java

- 에디터 발행 후 수정한 값을 db에 입력하는 기능 구현
- 타이틀 배경화면 불러오기 기능 구현
- 에디터 선택 값 수정 기능 구현

250227 Feat

---

appfinal/src/pages/slog/SlogWrite.jsx
springfinal/src/main/java/com/kh/springfinal/slog/SlogMapper.java

250227: FEAT

---

appfinal/src/pages/slog/Slog.jsx
appfinal/src/pages/slog/SlogCard.jsx
appfinal/src/pages/slog/SlogDetail.jsx
appfinal/src/pages/slog/SlogList.jsx
appfinal/src/pages/slog/SlogWrite.jsx
appfinal/src/redux/slogDetailSlice.jsx
appfinal/src/redux/slogSlice.jsx
springfinal/src/main/java/com/kh/springfinal/slog/SlogController.java
springfinal/src/main/java/com/kh/springfinal/slog/SlogMapper.java
springfinal/src/main/java/com/kh/springfinal/slog/SlogVo.java

- 상세조회 타이틀 수정
- 리스트 (작성자, 독채이름 추가)

250228: FEAT

---

appfinal/src/pages/slog/KakaoShare.jsx
appfinal/src/pages/slog/SlogDetail.jsx

250304 Feat

---

appfinal/src/components/map/MapRec.jsx
appfinal/src/pages/slog/Slog.jsx
appfinal/src/pages/slog/SlogCard.jsx
appfinal/src/pages/slog/SlogDetail.jsx
appfinal/src/redux/slogDetailSlice.jsx
appfinal/src/redux/slogSlice.jsx
springfinal/src/main/java/com/kh/springfinal/slog/SlogController.java
springfinal/src/main/java/com/kh/springfinal/slog/SlogMapper.java
springfinal/src/main/java/com/kh/springfinal/slog/SlogService.java
springfinal/src/main/java/com/kh/springfinal/slog/SlogVo.java

- 맵 숙소 정보 출력
- S-LOG 상세 정보 화면 UI 수정

250305: FEAT , DESIGN

---

appfinal/src/pages/slog/SlogCard.jsx
appfinal/src/pages/slog/SlogDetail.jsx
appfinal/src/pages/slog/SlogWrite.jsx

- S-LOG list 레이아웃 수정
- S-LOG detail 사진 크기, 레이아웃 수정

250305 Design

---

appfinal/src/pages/slog/SlogDetail.jsx

250305: FEAT

---

appfinal/src/pages/slog/SlogDetail.jsx
springfinal/src/main/java/com/kh/springfinal/slog/SlogController.java

250306: Design

---

appfinal/src/pages/slog/SlogDetail.jsx

250306: FEAT S-log 수정권한 수정

---

appfinal/src/components/map/KaKaoMap.jsx
appfinal/src/components/map/MapRec.jsx
appfinal/src/pages/slog/SlogDetail.jsx
appfinal/src/pages/slog/SlogWrite.jsx
springfinal/src/main/java/com/kh/springfinal/slog/SlogController.java

- 카카오맵 로드뷰 기능 구현
- 카카오맵 검색 기능 구현
- S-LOG 동영상, 구분선, 표 삽입 기능 구현

250312: FEAT 카카오맵 로드뷰, 검색기능 S-LOG 동영상,구분선,표 삽입 기능 구현

---

appfinal/src/pages/slog/SlogDetail.jsx
appfinal/src/pages/slog/SlogWrite.jsx
appfinal/src/pages/traffic/Traffic.jsx

250312: FEAT 표, 동영상 삽입 기능 수정

---

appfinal/src/components/kakaopage/KakaoMsg.jsx

20250312 FEAT:결재내역 나에게보내기

---

appfinal/src/pages/slog/SlogWrite.jsx

250317: FEAT 구분선 기능 수정

---

appfinal/src/pages/slog/KakaoShare.jsx
appfinal/src/pages/slog/SlogDetail.jsx
appfinal/src/pages/slog/SlogList.jsx
appfinal/src/pages/slog/SlogWrite.jsx
appfinal/src/pages/traffic/Bus.jsx
appfinal/src/pages/traffic/Train.jsx
springfinal/src/main/java/com/kh/springfinal/slog/SlogController.java

250317 : FEAT fetch 경로 BASE_URL로 수정

---

springfinal/src/main/java/com/kh/springfinal/bus/BusApi.java
springfinal/src/main/java/com/kh/springfinal/train/TrainApi.java

250317: FEAT 버스, 기차 API 수정

---

appfinal/src/components/Middle.jsx
appfinal/src/pages/slog/SlogDetail.jsx

- 스테이 예약하기 경로 설정
- 홈 슬라이드 width 값 수정

250318: FEAT 스테이 예약하기 경로 설정

---

springfinal/src/main/java/com/kh/springfinal/train/TrainApi.java

250319: Refactor 출력문 제거

---

springfinal/src/main/java/com/kh/springfinal/train/TrainApi.java

250319: Comment 스케줄러 주석처리

---

appfinal/src/pages/slog/KakaoShare.jsx

250319: Fix 카카오 공유 경로 수정
